apiVersion: v1
kind: ConfigMap
metadata:
  name: cart-config
  namespace: roboshop
data: 
  REDIS_HOST: "redis"
  CATALOGUE_HOST: "http://catalogue:8080"
  CATALOGUE_PORT: "8080"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: roboshop
  labels:
    project: roboshop
    component: cart
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      component: cart
      environment: dev
  template:
    metadata:
      labels:
        project: roboshop
        component: cart
        environment: dev
    spec:
      containers:
      - name: cart
        image: hanumanth897/cart:4.0.0
        envFrom:
        - configMapRef:
            name: cart-config
---
apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: roboshop
  labels:
    project: roboshop
    component: cart
    environment: dev
spec:
  selector:
    project: roboshop
    component: cart
    environment: dev
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

