apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue-config
  namespace: roboshop
data: 
  MONGO: "true"
  MONGO_URL: "mongodb://mongodb:27017/catalogue"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    project: roboshop
    component: catalogue
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      component: catalogue
      environment: dev
  template:
    metadata:
      labels:
        project: roboshop
        component: catalogue
        environment: dev
    spec:
      containers:
      - name: catalogue
        image: hanumanth897/catalogue:4.0.0
        envFrom:
        - configMapRef:
            name: catalogue-config
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    project: roboshop
    component: catalogue
    environment: dev
spec:
  selector:
    project: roboshop
    component: catalogue
    environment: dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

